### ISSUE TITLE
adult links in lieu of PDF

### ISSUE THREAD

**Issue by mogando668** [tobiasgrosser/polyhedral.info#21]
at url

 [http://polyhedral.info/#FEAUTRIER1988PARAMETRIC]

under the 9th item in **Bibliography section** :###  Parametric Integer Programming,

attempts to click on the "eyeball" icon to view the PDF redirects the visitor to an explicit adult site. Thanks for your time.

**Comment by tobiasgrosser** [comment]
This should be resolved now. Thank you for the report.
